{{- range $name, $config := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base.configMapName" (dict "cmName" $name "context" $) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "base.labels" $ | nindent 4 }}
{{- if $config.data }}
data:
  {{- toYaml $config.data | nindent 2 }}
{{- end }}
{{- if $config.binaryData }}
binaryData:
  {{- toYaml $config.binaryData | nindent 2 }}
{{- end }}
{{- end }}
